//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     161
#define IDB_BITMAP4                     162
#define IDB_BACK1                       162
#define IDB_OPEND                       163
#define IDB_START                       164
#define IDB_TOWER1                      165
#define IDB_BITMAP5                     166
#define IDB_TOWER2                      166
#define IDB_BITMAP7                     168
#define IDB_E_DOG_WALK_0                168
#define IDB_UPGRADE                     169
#define IDB_UPGRADE_BLACK               170
#define IDB_EMPTY_BLOCK                 171
#define IDB_0_N                         172
#define IDB_1_N                         173
#define IDB_2_N                         174
#define IDB_3_N                         175
#define IDB_4_N                         176
#define IDB_5_N                         177
#define IDB_6_N                         178
#define IDB_7_N                         179
#define IDB_8_N                         180
#define IDB_9_N                         181
#define IDB_SLASH                       182
#define IDB_BITMAP6                     183
#define IDB_E_DOG_WALK_1                184
#define IDB_BITMAP9                     185
#define IDB_E_DOG_WALK_2                185
#define IDB_F_MARSHMELLOW_HIT_0         186
#define IDB_F_MARSHMELLOW_HIT_1         187
#define IDB_F_MARSHMELLOW_HIT_2         188
#define IDB_F_MARSHMELLOW_WALK_0        189
#define IDB_F_MARSHMELLOW_WALK_1        190
#define IDB_F_MARSHMELLOW_WALK_2        191
#define IDB_0_T                         192
#define IDB_1_T                         193
#define IDB_2_T                         194
#define IDB_3_T                         195
#define IDB_4_T                         196
#define IDB_5_T                         197
#define IDB_6_T                         198
#define IDB_7_T                         199
#define IDB_8_T                         200
#define IDB_9_T                         201
#define IDB_BITMAP8                     202
#define IDB_SLASH_T                     202
#define IDB_BITMAP10                    203
#define IDB_BACK2                       204
#define IDB_BACK3                       205
#define IDB_BACK4                       206
#define IDB_BACK5                       207
#define IDB_BACK6                       208
#define IDB_BACK7                       209
#define IDB_BACK8                       210
#define IDB_BACK9                       211
#define IDB_BACK10                      212
#define IDB_LOSE                        217
#define IDB_WIN                         218
#define IDB_OVERBACK                    219
#define IDB_OPTION                      220
#define IDB_MAP                         221
#define IDB_STAGE1                      222
#define IDB_STAGE2                      223
#define IDB_STAGE3                      224
#define IDB_STAGE4                      225
#define IDB_STAGE5                      226
#define IDB_STAGE6                      227
#define IDB_STAGE7                      228
#define IDB_STAGE8                      229
#define IDB_STAGE9                      230
#define IDB_STAGE10                     231
#define IDB_STAGE_BACK                  232
#define IDB_WIN_OPTION                  234
#define IDB_CLOSE                       236
#define IDB_GOBACK                      237
#define IDB_BITMAP11                    238
#define IDB_BATTLE                      238
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        239
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
